### ISSUE TITLE
Help with burning the firmware using FTDI module

### ISSUE THREAD

**Issue by tibyanne** [mstrens/grbl_6axis_on_stm32#3]
Hello @mstrens, excuse my ignorance but how can I burn the firmware using an FTDI module?, I don't have STlink programmer.

and does the 4th axis works nativle as a rotary axis on this firmware?

Thank you

**Comment by mstrens** [comment]
I have no experience with FTDI for STM32 but have a look at this video
https://www.youtube.com/watch?v=RVDSHQmTjfQ
Look mainly at the second part where a Hex file is loaded with a FTDI.
The Hex file can be generated with Atolic.

In order to use the 4th axis, you have to activate it in a file (config.h I think. It refers to something like A_AXIS, I would have to check). 
I do not know if it is handled as a linear axis or a rotary axis. Perhaps it depends on the letter used in the Gcode.
Best is to try and see.

**Comment by tibyanne** [comment]
Thanks for your quick reply sir,
I watched the video and I get it now, I need to know if the A-AXIS is linear or rotary and I don't have the knowledge to check the code to see by my self,  I will burn the hex and test to see if I can get some information.

Thanks again sir I appreciate it.

**Comment by iramuhammad** [comment]
Thanks for your quick reply sir,
I watched the video and I get it now, I need to know if the A-AXIS is linear or rotary and I don't have the knowledge to check the code to see by my self,  I will burn the hex and test to see if I can get some information.

Thanks again sir I appreciate it.
